<?php

/**
 * Implementation of hook fb_social_plugins_info
 */
function fb_social_recommendations_fb_social_plugins_info(){
  $info = array();
  $info['recommendations'] = array(
      'name' => 'recommendations', 
      'description' => 'recommendations button', 
  );
  
  return $info;
}


/**
 * Implementation of hook_ctools_plugin_api().
 */
function fb_social_recommendations_ctools_plugin_api($module, $api){
  if ($module == 'boxes' && $api == 'plugins') {
    return array(
        'version' => 1 
    );
  }
}

/**
 * Implementation of hook_boxes_plugins().
 */
function fb_social_recommendations_boxes_plugins(){
  $info = array();
  
  $info['fb_social_recommendations_boxes_recommendations'] = array(
      'title' => 'facebook social recommendations', 
      'handler' => array(
          'class' => 'fb_social_recommendations_box', 
          'file' => 'fb_social_recommendations_boxes.inc', 
          'path' => drupal_get_path('module', 'fb_social_recommendations'), 
          'parent' => 'fb_social_boxes_default' 
      ) 
  );
  
  return $info;
}

