<?php

/**
 * @file
 * Widgets show some info about the content and the social network.
 */

/**
 * Implementation of hook_service_links().
 */
function widget_services_service_links() {
  $links = array();

  $links['facebook_widget'] = array(
    'name' => t('Share on Facebook'),
    'link' => 'http://www.facebook.com/sharer.php',
    'description' => t('Share this post on Facebook'),
    'javascript' => array(
      'http://static.ak.fbcdn.net/connect.php/js/FB.Share',
      'facebook_share.js',
    ),
    'icon' => 'facebook.png',
    'style' => SERVICE_LINKS_STYLE_TEXT,
    'callback' => 'ws_facebook_widget_share',
  );
  $links['twitter_widget'] = array(
    'name' => 'Tweet Widget',
    'link' => 'http://twitter.com/share?url=<raw-encoded-short-url>&count=<data-count>&via=<data-via>&text=<raw-encoded-title>&counturl=<raw-encoded-url>',
    'icon' => 'twitter.png',
    'description' => t('Tweet This'),
    'attributes' => array('class' => 'twitter-share-button'),
    'javascript' => 'http://platform.twitter.com/widgets.js',
    'style' => SERVICE_LINKS_STYLE_EMPTY,
    'callback' => 'ws_twitter_widget_data',
  );
  $links['facebook_like'] = array(
    'name' => 'Facebook Like',
    'link' => 'http://www.facebook.com/plugins/like.php?href=<encoded-url>&layout=<layout>&show_faces=<show_faces>&action=<action>&colorscheme=<colorscheme>&width=<width>&height=<height>&font=<font>',
    'icon' => 'facebook.png',
    'description' => t('I Like it'),
    'javascript' => 'facebook_like.js',
    'style' => SERVICE_LINKS_STYLE_EMPTY,
    'callback' => 'ws_facebook_widget_like',
  );
  $links['digg_smart_button'] = array(
    'name' => 'Digg Smart Button',
    'link' => 'http://digg.com/submit?url=<raw-encoded-url>&title=<raw-encoded-title>&related=<related>&style=<style>',
    'icon' => 'digg.png',
    'description' => t('Digg It'),
    'javascript' => 'http://digg.com/tools/diggthis.js',
    'style' => SERVICE_LINKS_STYLE_EMPTY,
    'callback' => 'ws_digg_smart_button_data',
    'attributes' => array('class' => 'DiggThisButton ' . variable_get('service_links_dsb_type', 'DiggCompact')),
  );
  $links['google_plus_one'] = array(
    'name' => 'Google Plus One',
    'link' => '<url>',
    'icon' => 'google.png',
    'description' => t('Plus it'),
    'javascript' => array(
      'https://apis.google.com/js/plusone.js',
      'google_plus_one.js',
    ),
    'style' => SERVICE_LINKS_STYLE_EMPTY,
    'callback' => 'ws_google_plus_one_data',
  );

  return $links;
}

/**
 * Callback function for Twitter Widget.
 */
function ws_twitter_widget_data(&$service, $subst) {
  static $vars;

  if (!isset($vars)) {
    $vars['tags'] = array(
      'count' => '<data-count>',
      'via' => '<data-via>',
    );

    $vars['subst'] = array(
      'count' => variable_get('service_links_tw_data_count', 'horizontal'),
      'via' => urlencode(variable_get('service_links_tw_data_via' , '')),
    );
  }
  
  $service['url'] = str_replace($vars['tags'], $vars['subst'], $service['url']);
}

/**
 * Callback function for Facebook Share Widget.
 */
function ws_facebook_widget_share(&$service, $subst) {
  static $fs_settings;

  if (!isset($fs_settings)) {
    $fs_settings = array(
      'type' => variable_get('service_links_fs_type', 'button_count'),
    );

    drupal_add_js(array('ws_fs' => $fs_settings), 'setting');
  }

  $service['attributes']['rel'] = $subst['url'];
}

/**
 * Callback function for Facebook Like Widget.
 */
function ws_facebook_widget_like(&$service, $subst) {
  static $vars;

  if (!isset($vars)) {
    $vars['tags'] = array(
      'layout' => '<layout>',
      'show_faces' => '<show_faces>',
      'action' => '<action>',
      'colorscheme' => '<colorscheme>',
      'font' => '<font>',
      'width' => '<width>',
      'height' => '<height>',
    );

    $vars['subst'] = array(
      'layout' => variable_get('service_links_fl_layout', 'button_count'),
      'show_faces' => variable_get('service_links_fl_show_faces', 'false'),
      'action' => variable_get('service_links_fl_action', 'like'),
      'colorscheme' => variable_get('service_links_fl_colorscheme', 'light'),
      'font' => variable_get('service_links_fl_font', ''),
      'width' => variable_get('service_links_fl_width', '100'),
      'height' => '21',
    );

    $fl_settings = array(
      'width' => $vars['subst']['width'],
      'height' => '21',
    );

    switch ($vars['subst']['layout']) {
      case 'standard':
        $fl_settings['height'] = '80';
        $vars['subst']['height'] = '80';
        break;
      case 'box_count':
        $fl_settings['height'] = '65';
        $vars['subst']['height'] = '65';
        break;
      //case 'button_count':
        //$fl_settings['height'] = 21;
        //$vars['subst']['height'] = '21';
        //break;
    }

    drupal_add_js(array('ws_fl' => $fl_settings), 'setting');
  }

  $service['url'] = str_replace($vars['tags'], $vars['subst'], $service['url']);
}

/**
 * Callback function for Digg Button.
 */
function ws_digg_smart_button_data(&$service, $subst) {
  static $vars;

  if (!isset($vars)) {
    $vars['tag'] = array(
      'related' => '<related>',
      'style' => '<style>',
    );

    $vars['subst'] = array(
      'related' => variable_get('service_links_dsb_related', 'yes'),
      'style' => variable_get('service_links_dsb_style', 'yes'),
    );
  }

  // teaser on rel used as description ?
  $service['url'] = str_replace($vars['tags'], $vars['subst'], $service['url']);
}

/**
 * Callback function for Google Plus One.
 */
function ws_google_plus_one_data(&$service, $subst) {
  static $gpo_settings;

  if (!isset($gpo_settings)) {
    $gpo_settings = array(
      'type' => variable_get('service_links_gpo_type', ''),
      'counter' => variable_get('service_links_gpo_counter', TRUE),
    );

    drupal_add_js(array('ws_gpo' => $gpo_settings), 'setting');
  }
}

/**
 * Implementation of hook_menu().
 */
function widget_services_menu() {
  $items = array();

  $items['admin/settings/service_links/widgets'] = array(
    'title' => 'Widgets',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('widget_services_admin'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'parent' => 'admin/settings/service_links',
    'file' => 'widget_services.admin.inc',
  );

  return $items;
}
